blank_issues_enabled: false
contact_links:
  - name: Get Help with This Stack
    url: https://github.com/freekrai/directus-fly/discussions/new?category=q-a
    about:
      Help with this stack itself. 
  - name: Feature Request for This Stack
    url: https://github.com/freekrai/directus-fly/discussions/new?category=ideas
    about:
      I appreciate you taking the time to improve Remix Blog with your ideas, but let's
      use the Discussions for this instead of the issues tab ğŸ™‚.
  - name: Get Remix Help
    url: https://github.com/remix-run/remix/discussions/new?category=q-a
    about:
      If you can't get something to work the way you expect, open a question in
      the Remix discussions.
  - name: ğŸ’¬ Remix Discord Channel
    url: https://rmx.as/discord
    about: Interact with other people using Remix ğŸ’¿
  - name: ğŸ’¬ New Updates (Twitter)
    url: https://twitter.com/remix_run
    about: Stay up to date with Remix news on twitter
  - name: ğŸ¿ Remix YouTube Channel
    url: https://rmx.as/youtube
    about: Are you a tech lead or wanting to learn more about Remix in depth? Checkout the Remix YouTube Channel
